name: Docker Compose

on: [push]

jobs:
  build:
    if: ${{ github.event_name == 'push' && !contains( toJson(github.event.commits.*.message),'#skip') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run the test commands
        run: docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"