name: Python application

on: [push]

jobs:
  build:
    if: ${{ github.event_name == 'push' && !contains( toJson(github.event.commits.*.message),'#skip') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test
      run: |
        cd app
        python manage.py test
    - name: Run linting (flake8)
      run: |
        cd app
        python manage.py flake8
